# FILE: .github/dependabot.yml
# CREATED: 2025-04-05 16:25:53
#
# PURPOSE:
# This configuration file manages automated dependency updates for the project
# using GitHub's Dependabot feature.

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Pacific/Honolulu"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    versioning-strategy: "auto"
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "${{secrets.DEPENDENCY_REVIEWER}}"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Pacific/Honolulu"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "automerge"