#!/usr/bin/env sh
# FILE: .husky/commit-msg
# CREATED: 2025-04-05 16:27:23
#
# PURPOSE:
# Git hook to validate commit messages according to conventional commits specification

. "$(dirname -- "$0")/_/husky.sh"

pnpm commitlint --edit ${1}